stages:
  - tf_apply
  - tf_destroy

terraform_apply:
  stage: tf_apply
  tags:
    - test_job
    - wordpress
  script:
    - cd ./terraform
    - terraform init
    - terraform apply -auto-approve
  variables:
    TF_VAR_AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
    TF_VAR_AWS_SECRET_KEY: ${AWS_SECRET_KEY}

terraform_destroy:
  stage: tf_destroy
  tags:
    - test_job
    - wordpress
  script:
    - terraform destroy -auto-approve
  variables:
    TF_VAR_AWS_ACCESS_KEY: $AWS_ACCESS_KEY
    TF_VAR_AWS_SECRET_KEY: $AWS_SECRET_KEY
  when: manual