stages:
  - downstream-pipelines

infrastructure:
  stage: downstream-pipelines
  trigger:
    include:
      - infrastructure/.gitlab-ci.yml
    strategy: depend

compose:
  stage: downstream-pipelines
  trigger:
    include:
      - install_application/.gitlab-ci.yml
    strategy: depend