stages:
  - downstream-pipelines

infrastructure:
  stage: downstream-pipelines
  trigger:
    include:
      - infrastructure/.gitlab-ci.yml
    strategy: depend

wordpress_compose:
  stage: downstream-pipelines
  trigger:
    include:
      - install_wordpress/.gitlab-ci.yml
    strategy: depend
  needs:
    - job: infrastructure

zabbix_compose:
  stage: downstream-pipelines
  trigger:
    include:
      - install_zabbix/.gitlab-ci.yml
    strategy: depend
  needs:
    - job: infrastructure