cache:
  paths:
    - ${CI_PROJECT_DIR}/ansible/hosts
  
stages:
  - deploy_wordpress

deploy_to_stage:
  stage: deploy_wordpress
  tags:
  - test_job
  - wordpress
  before_script:
    - FIRST_SERVER=$(cat ${CI_PROJECT_DIR}/ansible/hosts | sed -n '1p')
    - ssh-keyscan -H ${FIRST_SERVER} >> ~/.ssh/known_hosts
  script:
    - scp ${CI_PROJECT_DIR}/install_wordpress/stage/docker-compose.yaml gitlab-runner@${FIRST_SERVER}:~/docker-compose.yaml
    - envsubst < ${CI_PROJECT_DIR}/install_wordpress/deploy.sh|ssh gitlab-runner@${FIRST_SERVER}
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /stage/i

deploy_to_prod:
  stage: deploy_wordpress
  tags:
  - test_job
  - wordpress
  before_script:
    - FIRST_SERVER=$(cat ${CI_PROJECT_DIR}/ansible/hosts | sed -n '1p')
    - ssh-keyscan -H ${FIRST_SERVER} >> ~/.ssh/known_hosts
  script:
    - scp ${CI_PROJECT_DIR}/install_wordpress/prod/docker-compose.yaml gitlab-runner@${FIRST_SERVER}:~/docker-compose.yaml
    - envsubst < ${CI_PROJECT_DIR}/install_wordpress/deploy.sh|ssh gitlab-runner@${FIRST_SERVER}
    - echo "${FIRST_SERVER}:9000"
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /prod/i