variables:
  WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
  WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

cache:
  paths:
    - ${CI_PROJECT_DIR}/ansible/hosts
  
stages:
  - deploy_wordpress

deploy_to_stage:
  stage: deploy_wordpress
  tags:
  - test_job
  - wordpress
  before_script:
    - ls -la ${CI_PROJECT_DIR}/ansible
    - FIRST_SERVER=$(cat ${CI_PROJECT_DIR}/ansible/hosts | sed -n '1p')
    - ssh-keyscan -H ${FIRST_SERVER} >> ~/.ssh/known_hosts
  script:
    - echo ${FIRST_SERVER}
    - scp ${CI_PROJECT_DIR}/install_wordpress/stage/docker-compose.yaml gitlab-runner@${FIRST_SERVER}:~/docker-compose.yaml
    - sudo usermod -aG docker gitlab-runner
    - sudo chmod 666 /var/run/docker.sock
    - |
      ssh gitlab-runner@${FIRST_SERVER} << 'EOF'
      export WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      export WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      export WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      export MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      sudo docker-compose -f /home/gitlab-runner/docker-compose.yaml up -d
      EOF
    # - envsubst < ${CI_PROJECT_DIR}/install_wordpress/deploy.sh|ssh gitlab-runner@${FIRST_SERVER}
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /stage/i

deploy_to_prod:
  stage: deploy_wordpress
  tags:
  - test_job
  - wordpress
  before_script:
    - ls -la ${CI_PROJECT_DIR}/ansible
    - FIRST_SERVER=$(cat ${CI_PROJECT_DIR}/ansible/hosts | sed -n '1p')
    - ssh-keyscan -H ${FIRST_SERVER} >> ~/.ssh/known_hosts
  script:
    - scp ${CI_PROJECT_DIR}/ansible/prod/docker-compose.yaml gitlab-runner@${FIRST_SERVER}:~/docker-compose.yaml
    - envsubst < ${CI_PROJECT_DIR}/install_wordpress/deploy.sh|ssh gitlab-runner@${FIRST_SERVER}
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /prod/i