variables:
    WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  
  stages:
    - deploy
  deploy_to_stage:
    stage: deploy
    dependencies:
      - create-variable
    tags:
    - test_job
    - wordpress
    before_script:
      - source <(sed -n '1p' ip_address.env)
    script:
      - scp ${CI_PROJECT_DIR}/install_wordpress/stage/docker-compose.yaml gitlab-runner@${IP_ADDRESS}:~/docker-compose.yaml
      # - ssh gitlab-runner@remote_server 'export WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST} WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD} && docker-compose -f ~/docker-compose.yaml up -d'
    only:
      variables:
      - ${CI_COMMIT_MESSAGE} =~ /stage/i

  prod:
    - deploy
  deploy_to_prod:
    prod: deploy
    dependencies:
      - create-variable
    tags:
    - test_job
    - wordpress
    before_script:
      - source <(sed -n '1p' ip_address.env)
    script:
      - scp ${CI_PROJECT_DIR}/ansible/prod/docker-compose.yaml gitlab-runner@remote_server:~/docker-compose.yaml
      - ssh gitlab-runner@remote_server 'export WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST} WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD} && docker-compose -f ~/docker-compose.yaml up -d'
    only:
      variables:
      - ${CI_COMMIT_MESSAGE} =~ /prod/i