version: "3.9"

services:
  zabbix-mariadb:
    image: mariadb:11.0.3
    container_name: zabbix-mariadb
    hostname: zabbix-mariadb
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: zabbix
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /opt/zabbix/mariadb/data:/var/lib/mysql
    networks:
      - zabbix_network

  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    hostname: zabbix-server
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - zabbix-mariadb
    networks:
      - zabbix_network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web
    hostname: zabbix-web
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Europe/Moscow"
    ports:      
      - 8080:8080
    depends_on:
      - zabbix-mariadb
      - zabbix-server
    networks:
      - zabbix_network

networks:
  zabbix_network: