---
- name: Установка Docker и Docker Compose
  hosts: all
  become: true

  tasks:
    - name: Wait for SSH to come up
      wait_for:
        port: 22
        delay: 10
        timeout: 300
        state: started

    - name: apt update
      apt:
        update_cache: yes

    - name: Docker Install
      apt:
        name: docker.io
        state: present
    
    - name: Docker-Compose Install
      apt:
        name: docker-compose
        state: present

    - name: Is Docker start?
      systemd:
        name: docker
        state: started
        enabled: yes